### PR TITLE
fixes #3

### LINKED ISSUE #3: windows - fails to compile with canvas 1.2.4 - request to use 1.2.3 for now
```canvas-browserify``` fails to compile on windows with ```canvas@1.2.4```

Reason: see https://github.com/Automattic/node-canvas/issues/591

```canvas-browserify``` package.json specifies in dependencies ```canvas: "1"``` and hence will try to install latest ```canvas``` ...

Request: until ```canvas``` is fixed, could you use ```canvas: "<1.2.4"``` or something similar?

### PR DESCRIPTION
**Pull request by timknip**
Fixes https://github.com/dominictarr/canvas-browserify/issues/3

### CODE REVIEW

**Comment by dominictarr** [comment]
hey, i havn't used this module in _ages_ would you like to take this one over?
I'll add you as contributor and npm owner and you can merge this yourself.

**Comment by timknip** [comment]
LOL!

Seriously: sure.

Guess it won't be too much effort considering it's a wrapper.

Got some often updated apps using canvas-browserify now failing to build. So for me there's some urgency. 

Ok if I contact you when needed? Guess it won't be necessary, but just in case.

Cheers,
Tim

**Comment by dominictarr** [comment]
okay just gave you the keys to the lamborghini! have fun.

**Comment by dominictarr** [comment]
sure @ me if you need anything but i'm not really sure how i'll be able to help. to be honest i gave up on this module because the deps where too hard to install on archlinux... next time i need something like this i think i will just use svg instead.

**Comment by timknip** [comment]
Thanks! v1.1.2 is now available on npm btw.
I'll update ```canvas-browserify```  when ```canvas``` is fixed and builds again on windows.

**Comment by dominictarr** [comment]
:+1:

**Comment by timknip** [comment]
Hiya Dominic,

Could you shed some light on
https://github.com/Automattic/node-canvas/pull/589#issuecomment-125984476 ?

The node-canvas dudes want to make it browserifyable :)

Cheers,
Tim

2015-07-27 15:29 GMT+02:00 Dominic Tarr notifications@github.com:

**Pull request merged**
